#Task 1: My first square
import turtle
turtle.fillcolor("Brown")
turtle.begin_fill()
turtle.pencolor("Red")
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.end_fill()

#Task 2 Measurements in programing
turtle.fillcolor("Blue")
turtle.begin_fill()
turtle.pencolor("Purple")
turtle.forward(180)
turtle.right(90)
turtle.forward(180)
turtle.right(90)
turtle.forward(180)
turtle.right(90)
turtle.forward(180)
turtle.end_fill()
turtle.penup()
turtle.pendown()

#Task 3: Draw a triangle
turtle.pensize(5)
turtle.forward(200)
turtle.left(120)
turtle.forward(200)
turtle.left(120)
turtle.forward(200)
turtle.left(120)

#Task 4: Draw a rectangle
turtle.fillcolor("orange")
turtle.begin_fill()
turtle.pencolor("Red")
turtle.forward(120)
turtle.right(90)
turtle.forward(190)
turtle.right(90)
turtle.forward(120)
turtle.right(90)
turtle.forward(190)
turtle.end_fill()
turtle.penup()
turtle.pendown()

#Task 5: Different Shapes
#pentagon
turtle.fillcolor("pink")
turtle.begin_fill()
turtle.pencolor("green")
turtle.forward(100)
turtle.right(72)
turtle.forward(100)
turtle.right(72)
turtle.forward(100)
turtle.right(72)
turtle.forward(100)
turtle.right(72)
turtle.forward(100)
turtle.right(72)
turtle.end_fill()
turtle.penup()
turtle.pendown()

#hexagon
turtle.fillcolor("yellow")
turtle.begin_fill()
turtle.pencolor("green")
turtle.forward(100)
turtle.right(60)
turtle.forward(100)
turtle.right(60)
turtle.forward(100)
turtle.right(60)
turtle.forward(100)
turtle.right(60)
turtle.forward(100)
turtle.right(60)
turtle.forward(100)
turtle.right(60)
turtle.end_fill()
turtle.penup()
turtle.pendown()

#octagon
turtle.fillcolor("red")
turtle.begin_fill()
turtle.pencolor("pink")
turtle.forward(100)
turtle.right(45)
turtle.forward(100)
turtle.right(45)
turtle.forward(100)
turtle.right(45)
turtle.forward(100)
turtle.right(45)
turtle.forward(100)
turtle.right(45)
turtle.forward(100)
turtle.right(45)
turtle.forward(100)
turtle.right(45)
turtle.forward(100)
turtle.right(45)
turtle.end_fill()
turtle.penup()
turtle.pendown()

#decagon
turtle.fillcolor("navy blue")
turtle.begin_fill()
turtle.pencolor("turquoise")
turtle.forward(100)
turtle.right(36)
turtle.forward(100)
turtle.right(36)
turtle.forward(100)
turtle.right(36)
turtle.forward(100)
turtle.right(36)
turtle.forward(100)
turtle.right(36)
turtle.forward(100)
turtle.right(36)
turtle.forward(100)
turtle.right(36)
turtle.forward(100)
turtle.right(36)
turtle.forward(100)
turtle.right(36)
turtle.forward(100)
turtle.right(36)
turtle.end_fill()
turtle.penup()
turtle.pendown()
"""
"""  

#Task 6: Create House
#house base(square)
import turtle
turtle.fillcolor("#dea767")
turtle.begin_fill()
turtle.pencolor("brown")
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.right(90)
turtle.forward(200)
turtle.end_fill()

#roof(triangle)
turtle.pensize()
turtle.fillcolor("#793d0c")
turtle.begin_fill()
turtle.right(30)
turtle.forward(200)
turtle.right(120)
turtle.forward(200)
turtle.right(120)
turtle.forward(200)
turtle.right(120)
turtle.end_fill()


#Lesson 2: Looping
import turtle
turtle.fillcolor("light blue")
turtle.begin_fill()
turtle.pencolor("blue")
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(100)
turtle.end_fill()
